version: '3.9'

services:
  postgresdb:
    container_name: postgresdb
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    
  portfolio:
    container_name: portfolio
    build: 
      context: ./portfolio/.
    env_file: .env
    ports:
      - 90:8000
    volumes:
      - ./portfolio:/app
  
  todoapp:
    container_name: todoapp
    build:
      context: ./todoapp/.
    env_file: .env
    ports:
      - 91:8000
    volumes:
      - ./todoapp:/app

  alwazah:
    container_name: alwazah
    build:
      context: ./alwazah/.
    env_file: .env
    ports:
      - 92:8000
    volumes:
      - ./alwazah:/app
    depends_on:
      - postgresdb
  
  kwin:
    container_name: kwin
    build:
      context: ./kwin/.
    env_file: .env
    ports:
      - 93:8000
    volumes:
      - ./kwin:/app
    depends_on:
      - postgresdb

volumes:
  postgres-data:
  portfolio:
  todoapp:
  alwazah:
  kwin: