version: '3.9'

services:
  portfolio:
    build: 
      context: ./portfolio/.
    ports:
      - 90:8000
    volumes:
      - ./portfolio:/app
  
  todoapp:
    build:
      context: ./todoapp/.
    ports:
      - 91:8000
    volumes:
      - ./todoapp:/app
volumes:
  portfolio:
  todoapp: