# Generated by Django 4.1.1 on 2022-09-13 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='_id',
            new_name='id',
        ),
    ]
