# Generated by Django 5.0.4 on 2024-04-07 14:17

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Enter the book's natural language (e.g. English, French, Japanese etc.)",
                        max_length=200,
                    ),
                ),
            ],
        ),
        migrations.AlterModelOptions(
            name="book",
            options={"ordering": ["title", "author"]},
        ),
        migrations.AlterModelOptions(
            name="bookinstance",
            options={
                "ordering": ["due_back"],
                "permissions": (("can_mark_returned", "Set book as returned"),),
            },
        ),
        migrations.AddField(
            model_name="bookinstance",
            name="borrower",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="isbn",
            field=models.CharField(
                help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>',
                max_length=13,
                unique=True,
                verbose_name="ISBN",
            ),
        ),
        migrations.AlterField(
            model_name="bookinstance",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                help_text="Unique ID for this particular book across whole library",
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="bookinstance",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("d", "Maintenance"),
                    ("o", "On loan"),
                    ("a", "Available"),
                    ("r", "Reserved"),
                ],
                default="d",
                help_text="Book availability",
                max_length=1,
            ),
        ),
        migrations.AddConstraint(
            model_name="language",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                name="language_name_case_insensitive_unique",
                violation_error_message="A language with the same name already exists.",
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="language",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="catalog.language",
            ),
        ),
    ]
